### ISSUE TITLE
No explanation for could not find function "%>%"

### ISSUE THREAD

**Issue by emmaggg** [willcrichton/r-autota#7]
<img width="1414" alt="Screen Shot 2020-02-28 at 8 56 19 AM" src="https://user-images.githubusercontent.com/61179236/75568549-545f6e80-5a08-11ea-9e0b-498d8ace14cf.png">
No display when meeting this error: could not find function "%>%"

`Error in us_stu_full %>% select(CNTSCHID, CNTSTUID, paste0("PV", 1:10,  : 
  could not find function "%>%"
Run `rlang::last_error()` to see where the error occurred.
Registered S3 methods overwritten by 'lme4':
  method                          from
  cooks.distance.influence.merMod car 
  influence.merMod                car 
  dfbeta.influence.merMod         car 
  dfbetas.influence.merMod        car 
Registered S3 methods overwritten by 'RcppEigen':
  method               from         
  predict.fastLm       RcppArmadillo
  print.fastLm         RcppArmadillo
  summary.fastLm       RcppArmadillo
  print.summary.fastLm RcppArmadillo
Registered S3 method overwritten by 'statnet.common':
  method          from  
  sort.data.frame memisc`

**Comment by willcrichton** [comment]
Fixed in f670cfd
